### LOGIN COMO ASISTENTE PARA GESTIONAR PERSONAL
# @name loginAsistente
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "asistente@empresa.com",
  "password": "asistentepassword123"
}

### LOGIN COMO ADMIN PARA ELIMINAR FISICAMENTE A PERSONAL
# @name loginAsistente
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "juanchispita@fosforos.com",
  "password": "password123"
}

### Token de Asistente
@token = {{loginAsistente.response.body.token}}

### 1. OBTENER LISTA DE USUARIOS ACTIVOS
GET http://localhost:3000/api/users
Authorization: Bearer {{token}}

### 2. REGISTRAR UN USUARIO SIN PROPORCIONAR CONTRASEÑA
POST http://localhost:3000/api/users/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Pedro Desactivame",
  "email": "pedro@fosforos.com",
  "role": "TECNICO"
}

### 3. BORRADO LÓGICO (Desactivar Técnico)
# Reemplazar ID_USER
PATCH http://localhost:3000/api/users/6a1869e652088c64e013d2b0/deactivate
Authorization: Bearer {{token}}

### 3. ACTUALIZAR DATOS DE UN USUARIO
PUT http://localhost:3000/api/users/6a1869e652088c64e013d2b0
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Pedro Borrame",
  "email": "pedro2@fosforos.com",
  "role": "GERENTE"
}

### C. BORRADO FÍSICO (Eliminar por error de carga)
# Reemplazar ID_USER
DELETE http://localhost:3000/api/users/6a1869e652088c64e013d2b0
Authorization: Bearer {{token}}