### FIXFACTORY - AUTHENTICATION & ROLES TEST

### 1. Registrar un ADMIN (Super Usuario)
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Admin Central",
  "email": "admin@fixfactory.com",
  "password": "adminpassword123",
  "role": "ADMIN",
  "company": "FixFactory Corp"
}

### 2. Registrar un GERENTE (Visión de Negocio)
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Gerente Comercial",
  "email": "gerente@empresa.com",
  "password": "gerentepassword123",
  "role": "GERENTE",
  "company": "Empresa Test A"
}

### 3. Registrar un ASISTENTE (Gestión de Personal)
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "RRHH Asistente",
  "email": "asistente@empresa.com",
  "password": "asistentepassword123",
  "role": "ASISTENTE",
  "company": "Empresa Test A"
}

### 4. Registrar un OPERARIO
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Operario de Máquina",
  "email": "operario@fixfactory.com",
  "password": "operariopass123",
  "role": "OPERARIO",
  "company": "Empresa Test A"
}

### 5. Registrar un TÉCNICO
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Técnico reparador",
  "email": "tecnico@fixfactory.com",
  "password": "tecnicoopass123",
  "role": "TECNICO",
  "company": "Empresa Test A"
}

### 6. LOGIN - Obtener Token de Acceso
# @name login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "admin@fixfactory.com",
  "password": "adminpassword123"
}

### VARIABLE PARA SIGUIENTES PRUEBAS
@authToken = {{login.response.body.token}}