### Crear una Máquina y copiar el "_id" recibido
POST http://localhost:3000/api/machines
Content-Type: application/json

{
  "code": "CNC-01",
  "name": "Torno CNC",
  "location": "Sector Mecanizado",
  "productionLine": "Línea 2",
  "installationDate": "2025-05-10"
}

### Reportar una Incidencia (RF-03)
# Reemplaza el valor de "machine" con el _id que copiaste arriba
POST http://localhost:3000/api/issues
Content-Type: application/json

{
  "machine": "69ef413bfca125fb3c9f8049", 
  "description": "Sobrecalentamiento en el motor principal tras 2 horas de uso.",
  "priority": "Alta",
  "reportedBy": "Matias Lorenzo"
}

### Listar todas las incidencias (Verás los datos de la máquina vinculada)
GET http://localhost:3000/api/issues

### Ver detalle de una incidencia específica
GET http://localhost:3000/api/issues/69ef415cfca125fb3c9f804a

### Cambiar estado a "En Proceso" (RF-05)
PUT http://localhost:3000/api/issues/69ef415cfca125fb3c9f804a
Content-Type: application/json

{
  "status": "En Proceso"
}

### Cambiar estado a "Solucionado"
PUT http://localhost:3000/api/issues/69ef415cfca125fb3c9f804a
Content-Type: application/json

{
  "status": "Solucionado"
}